[이진우] sprint4
codeit-sprint-fullstack/1-Sprint-Mission-BE pull request #1
Opened 2024-07-16 09:53 UTC by ajantang

## 요구사항

### 기본

- [x] Github에 스프린트 미션 PR을 만들어 주세요.
- [x] ‘https://sprint-mission-api.vercel.app/articles’ API를 이용하여 아래 함수들을 구현해 주세요.
	- [x] getArticleList() : GET 메서드를 사용해 주세요.
		- [x] page, pageSize, keyword 쿼리 파라미터를 이용해 주세요.
	- [x] getArticle() : GET 메서드를 사용해 주세요.
	- [x] createArticle() : POST 메서드를 사용해 주세요.
		- [x] request body에 title, content, image 를 포함해 주세요.
	- [x] patchArticle() : PATCH 메서드를 사용해 주세요.
	- [x] deleteArticle() : DELETE 메서드를 사용해 주세요.
- [x] fetch를 이용해 주세요.
	- [x] 응답의 상태 코드가 2XX가 아닐 경우, 에러메시지를 콘솔에 출력해 주세요.
- [x] .then() 메서드를 이용하여 비동기 처리를 해주세요.
- [x] .catch() 를 이용하여 오류 처리를 해주세요.
- [x] ‘https://sprint-mission-api.vercel.app/products’ API를 이용하여 아래 함수들을 구현해 주세요.
	- [x] getProductList() : GET 메서드를 사용해 주세요.
		- [x] page, pageSize, keyword 쿼리 파라미터를 이용해 주세요.
	- [x] getProduct() : GET 메서드를 사용해 주세요.
	- [x] createProduct() : POST 메서드를 사용해 주세요.
		- [x] request body에 name, description, price, tags, images 를 포함해 주세요.
	- [x] patchProduct() : PATCH 메서드를 사용해 주세요.
	- [x] deleteProduct() : DELETE 메서드를 사용해 주세요.
- [x]  axios를 이용해 주세요.
- [x]  async/await 을 이용하여 비동기 처리를 해주세요.
- [x]  try/catch 를 이용하여 오류 처리를 해주세요.
- [x]  구현한 함수들을 아래와 같이 파일을 분리해 주세요.
	- [x] export를 활용해 주세요.
	- [x] ProductService.js 파일 Product API 관련 함수들을 작성해 주세요.
	- [x] ArticleService.js 파일에 Article API 관련 함수들을 작성해 주세요.
- [x]  이외의 코드들은 모두 main.js 파일에 작성해 주세요.
	- [x] import를 활용해 주세요.
	 각 함수를 실행하는 코드를 작성하고, 제대로 동작하는지 확인해 주세요.

## 주요 변경사항

- 첫 업로드

## 스크린샷

![image](https://telegra.ph/file/6ce86fac8062d2957da2c.png)
![image](https://telegra.ph/file/b3b4913e3c2b43617e932.png)

## 멘토에게

- main.js에 test에 필요한 코드를 주석 처리해두었습니다.(UI 만드는 것은 보류 상태입니다.)
- 상세 명세는 함수 위에 주석으로 표시해뒀습니다.
- 필요 이상의 await 사용 확인 부탁드립니다.
- 로직 상 개선 사항을 알려주시면 좋겠습니다.

2024-07-24 14:21 UTC, wildCodingWarrior requested changes
node modules는 gitignore에 포함시켜주는 것이 좋습니다.
그리고 axios같은 패키지를 사용하고 설치했을 경우에는, 
package.json에 반영이 될 텐데 이번에는 안되어서 약간 이상하네요.

package.json에   
```
"dependencies": {
    "axios": "^1.7.2"
  }
```
가 있어야할텐데요.

불필요한 await의 경우 비동기 작업들을 모아서 한번에 Promise.all을 이용하면 처리할 수 있습니다.

또 코드 가독성을 위해 prettier 설치해서 사용해보시는건 어떨까요? 추천드립니다.

2024-07-24 14:21 UTC, wildCodingWarrior commented on package.json
> +}
여기에 script를 추가하면 실행을 더 쉽게 할 수 있습니다.
```
{
  "main": "index.js",
  "scripts": {
    "start": "node js/main.js"
  },
  "type": "module"
}
```

이렇게 되어있으면 터미널에서 yarn start, npm run start로 실행 가능합니다.

2024-07-24 14:21 UTC, wildCodingWarrior commented on js/ArticleService.js
> +const ARTICLE_API_ORIGIN = "https://sprint-mission-api.vercel.app";
base url 상수화 시킨 것 좋네요

2024-07-24 14:21 UTC, wildCodingWarrior commented on js/ArticleService.js
> +*/
주석 처리하실때 전체를 /** 내용 */ 이런식으로 감싸보세요. 이걸 JSDoc이라고 하는데, 함수에 커서 올리면 그 정보를 알려줄 때 유용합니다.

링크 참고하세요
https://jsdoc.app/about-getting-started

2024-07-24 14:21 UTC, wildCodingWarrior commented on js/ArticleService.js
> +export async function createAritcle(title, content, image)
오타 수정해주세요

2024-07-24 14:21 UTC, wildCodingWarrior commented on js/ArticleService.js
> +export async function pathArticle(id, body)
오타 수정해주세요

2024-07-26 12:36 UTC, ajantang commented
> node modules는 gitignore에 포함시켜주는 것이 좋습니다. 그리고 axios같은 패키지를 사용하고 설치했을 경우에는, package.json에 반영이 될 텐데 이번에는 안되어서 약간 이상하네요.
> 
> package.json에
> 
> ```
> "dependencies": {
>     "axios": "^1.7.2"
>   }
> ```
> 
> 가 있어야할텐데요.
> 
> 불필요한 await의 경우 비동기 작업들을 모아서 한번에 Promise.all을 이용하면 처리할 수 있습니다.
> 
> 또 코드 가독성을 위해 prettier 설치해서 사용해보시는건 어떨까요? 추천드립니다.

이 부분은 저도 자세히 확인을 해보겠습니다. 테스트 당시 npm start 명령어를 사용하여 작업했던 것으로 기억하는데, 스크립트도 그렇고 axios 삭제되어 있는 것도 그렇고, 다른 프로젝트 수정하면서 axios 등을 재설치한 적이 있는데, 그때 잘못 삭제를 한 것으로 추정됩니다.

2024-07-26 12:36 UTC, ajantang commented on js/ArticleService.js
> +export async function pathArticle(id, body)
수정했습니다. 감사합니다.

2024-07-26 12:36 UTC, ajantang commented on js/ArticleService.js
> +export async function createAritcle(title, content, image)
수정했습니다. 감사합니다.

2024-07-26 12:37 UTC, ajantang commented on js/ArticleService.js
> +*/
함수 설명 부분에만 /** */ 처리했습니다. 감사합니다.

2024-07-26 14:25 UTC, wildCodingWarrior approved these changes

2024-07-26 14:25 UTC, merged