[안재민] Sprint7
codeit-sprint-fullstack/1-Sprint-Mission-BE pull request #42
Opened 2024-08-15 08:04 UTC by mini-1018

## 요구사항

### 기본

중고마켓
- [x] mongoDB에서 PostgreSQL을 사용하도록 코드를 마이그레이션 해주세요.
공통

- [x] PostgreSQL를 이용해 주세요.
- [x] 데이터 모델 간의 관계를 고려하여 onDelete를 설정해 주세요.
- [x] 데이터베이스 시딩 코드를 작성해 주세요.
- [x] 각 API에 적절한 에러 처리를 해 주세요.
- [x] 각 API 응답에 적절한 상태 코드를 리턴하도록 해 주세요.

자유게시판
- [x] Article 스키마를 작성해 주세요.
- [x] id, title, content, createdAt, updatedAt 필드를 가집니다.
- [x] 게시글 등록 API를 만들어 주세요.
- [x] title, content를 입력해 게시글을 등록합니다.
- [x] 게시글 조회 API를 만들어 주세요.
- [x] id, title, content, createdAt를 조회합니다.
- [x] 게시글 수정 API를 만들어 주세요. 
- [x] 게시글 삭제 API를 만들어 주세요. 
- [x] 게시글 목록 조회 API를 만들어 주세요. 
- [x] id, title, content, createdAt를 조회합니다.
- [x] offset 방식의 페이지네이션 기능을 포함해 주세요.
- [x] 최신순(recent)으로 정렬할 수 있습니다. 
- [x] title, content에 포함된 단어로 검색할 수 있습니다. 
댓글
- [x] 댓글 등록 API를 만들어 주세요. 
- [x] content를 입력하여 댓글을 등록합니다.
- [x] 중고마켓, 자유게시판 댓글 등록 API를 따로 만들어 주세요.
- [x] 댓글 수정 API를 만들어 주세요.
- [x] PATCH 메서드를 사용해 주세요.
- [x] 댓글 삭제 API를 만들어 주세요.
- [x] 댓글 목록 조회 API를 만들어 주세요.
- [x] id, content, createdAt 를 조회합니다.
- [x] cursor 방식의 페이지네이션 기능을 포함해 주세요.
- [x] 중고마켓, 자유게시판 댓글 목록 조회 API를 따로 만들어 주세요.

### 심화

- [x]
- []

## 주요 변경사항
- app.js에 api를 작성하는 도중에 리액트처럼 컴포넌트화? 코드 분리 개념으로 작성하면 간결하고 유지보수가 편할 것 같아 찾아보던 중에 express 라우터에 대해 알게되어 적용하였습니다. 분리된 코드는 routes폴더에 구성하였습니다.
-

## 스크린샷

![image](이미지url)

## 멘토에게

- 데이터 시딩에 대해 대략적인 개념은 배웠지만 실제로 어떻게 쓰이는건지, 이것이 중요한건지 잘 모르겠습니다.
처음 개발 할 때 예를들어 prisma studio에서 하나하나 입력하는 것보다는 큰 틀?을 미리 잡고 넣어주면 편리해보이기는 하나 결국 시드 데이터도 누군가는 작성해야한다는 생각이 듭니다. 아니면 누군가 편리하게 가져다 쓰라고 시드데이터를 제공하는 곳이나 회사같은 곳에서는 초창기에 만든 시드데이터를 따로 저장해두고 관리하는지도 궁금합니다.
- 에러처리 관련해서 저는 에러핸들러를 따로 만들어서 import해오는식으로 했는데 이런식으로 하는게 맞는지... 직접 try catch로 해야할지 모르겠습니다. 제 생각에는 매번 try catch를 사용하기에는 코드도 복잡해지고 가독성이 많이 떨어지는 것 같아 사용했는데 한편으로는 많은 에러를 대비하지 못한 코드인 것 같습니다. 제가 아직 에러를 많이 겪지 못했고 그 에러에 대해 많이 다루지 않아 추후 멘토링 시간에 에러처리에 대해 조금 알려주시면 정말 감사하겠습니다!

2024-08-21 14:18 UTC, wildCodingWarrior requested changes
데이터 베이스 시딩에 대해서는, 다른 사람들과 같이 개발을 하거나, 이미 존재하는 프로젝트에서 신규 개발자로 투입되었다고 가정해봅시다.

서버에 올라가있는 운영 데이터베이스를 직접 다루는 건 엄금이고, 테스트 데이터베이스 조차도 자칫 만지다가 다른 개발자들이 사용 못하도록 만들 수도 있습니다. 그 경우에 신규 데이터베이스를 만들고 시딩을 진행하면 일관된 데이터로 안정적으로 시작할 수 있다는 장점이 있겠죠.

또한 지금은 테스트가 없는데, 테스트를 진행할 경우에도 미리 정의된 데이터가 필요하기도 합니다. 

핵심은 개발자들이 동일한 데이터를 이용해서 개발을 해야한다는 점입니다.

누군가는 그 데이터를 작성해야하는 것은 맞으나, 결국 그 데이터베이스를 구축하고 만드는 일에 포함되는 일입니다.

에러 처리의 경우 지금도 아주 잘 하셨습니다.
일반적으로 try-catch로 분리하면서 app.js 파일에 미들웨어로 추가하는 방법도 많이 사용합니다. 

이번 멘토링 시간에는 비즈니스 로직과 서비스 로직을 분리하는 방법에 대해서 잠깐 알아보면 좋겠습니다.

2024-08-21 14:18 UTC, wildCodingWarrior commented on prisma/schema.prisma
> +  price       Int
길이 제한을 걸 수 있겠네요. FE/BE 전부요

2024-08-21 14:18 UTC, wildCodingWarrior commented on routes/articles.js
> +        orderBy = { createdAt: 'asc' };
recent일 때 desc 아닌가요?

2024-08-21 14:18 UTC, wildCodingWarrior commented on routes/articleComments.js
> +    res.send(comment);
기본적으로 create 요청은 res.status(201) 로 응답하는게 좋겠습니다.

2024-08-21 14:18 UTC, wildCodingWarrior commented on routes/articleComments.js
> +    res.send(204);
이거 아마 deprecated 되어서 res.sendStatus(204) 사용해야하지 않나요?

2024-08-22 13:08 UTC, mini-1018 commented on routes/articles.js
> +        orderBy = { createdAt: 'asc' };
변경 완료입니다!

2024-08-22 13:09 UTC, mini-1018 commented on routes/articleComments.js
> +    res.send(204);
수정완료입니다!

2024-08-22 13:11 UTC, mini-1018 commented on routes/articleComments.js
> +    res.send(comment);
수정완료입니다!

2024-08-25 03:34 UTC, merged